### ISSUE TITLE
Widgets don't work

### ISSUE THREAD

**Issue by ittayd** [Bridgewater/scala-notebook#42]
new InputBox("")

    res3: com.bwater.notebook.widgets.InputBox = <InputBox widget>

No widget is displayed anywhere

**Comment by chrismyang** [comment]
Somehow the JS minification got more aggressive somehow?  Maybe version upgrade?

Separately, it was *extremely* confusing that that internal helper method is called `require`.  I went down a rabbit hole of "how the heck did this ever work?!" because we use curl not require.js!
